import { FormState, University } from "./CoverPageBuilder.types";

export const A4_W = 794;
export const A4_H = 1123;

export const UNIVERSITIES: University[] = [
  // Public Universities
  { id: "du", name: "University of Dhaka", short: "DU", logo: "" },
  { id: "buet", name: "Bangladesh University of Engineering and Technology", short: "BUET", logo: "" },
  { id: "ju", name: "Jahangirnagar University", short: "JU", logo: "" },
  { id: "cu", name: "University of Chittagong", short: "CU", logo: "" },
  { id: "ru", name: "University of Rajshahi", short: "RU", logo: "" },
  { id: "ku", name: "Khulna University", short: "KU", logo: "" },
  { id: "sust", name: "Shahjalal University of Science and Technology", short: "SUST", logo: "" },
  { id: "jnu", name: "Jagannath University", short: "JnU", logo: "" },
  { id: "iu", name: "Islamic University", short: "IU", logo: "" },
  { id: "hstu", name: "Hajee Mohammad Danesh Science and Technology University", short: "HSTU", logo: "" },
  { id: "mbstu", name: "Mawlana Bhashani Science and Technology University", short: "MBSTU", logo: "" },
  { id: "pstu", name: "Patuakhali Science and Technology University", short: "PSTU", logo: "" },
  { id: "bsmrstu", name: "Bangabandhu Sheikh Mujibur Rahman Science and Technology University", short: "BSMRSTU", logo: "" },
  { id: "bau", name: "Bangladesh Agricultural University", short: "BAU", logo: "" },
  { id: "cuet", name: "Chittagong University of Engineering and Technology", short: "CUET", logo: "" },
  { id: "kuet", name: "Khulna University of Engineering and Technology", short: "KUET", logo: "" },
  { id: "ruet", name: "Rajshahi University of Engineering and Technology", short: "RUET", logo: "" },
  { id: "butex", name: "Bangladesh University of Textiles", short: "BUTEX", logo: "" },

  // Private Universities
  { id: "uu", name: "Uttara University", short: "UU", logo: "https://res.cloudinary.com/dfoqasqnw/image/upload/header_logo_ldhtg9.png" },
  { id: "nsu", name: "North South University", short: "NSU", logo: "" },
  { id: "brac", name: "BRAC University", short: "BRACU", logo: "" },
  { id: "diu", name: "Daffodil International University", short: "DIU", logo: "" },
  { id: "aiub", name: "American International University-Bangladesh", short: "AIUB", logo: "" },
  { id: "ewu", name: "East West University", short: "EWU", logo: "" },
  { id: "iub", name: "Independent University, Bangladesh", short: "IUB", logo: "" },
  { id: "uiu", name: "United International University", short: "UIU", logo: "" },
  { id: "aust", name: "Ahsanullah University of Science and Technology", short: "AUST", logo: "" },
  { id: "ulab", name: "University of Liberal Arts Bangladesh", short: "ULAB", logo: "" },
  { id: "gub", name: "Green University of Bangladesh", short: "GUB", logo: "" },
  { id: "sub", name: "State University of Bangladesh", short: "SUB", logo: "" },
  { id: "seu", name: "Southeast University", short: "SEU", logo: "" },
  { id: "pu", name: "Premier University", short: "PU", logo: "" },
  { id: "su", name: "Stamford University Bangladesh", short: "SU", logo: "" },
  { id: "city", name: "City University", short: "CU", logo: "" },
  { id: "wub", name: "World University of Bangladesh", short: "WUB", logo: "" },
  { id: "sonargaon", name: "Sonargaon University", short: "SU", logo: "" },
  { id: "bu", name: "Bangladesh University", short: "BU", logo: "" },
  { id: "bubt", name: "Bangladesh University of Business and Technology", short: "BUBT", logo: "" },
  { id: "eub", name: "European University of Bangladesh", short: "EUB", logo: "" },
  { id: "iubat", name: "IUBAT – International University of Business Agriculture and Technology", short: "IUBAT", logo: "" },
  { id: "asu", name: "Atish Dipankar University of Science and Technology", short: "ADUST", logo: "" },
  { id: "manarat", name: "Manarat International University", short: "MIU", logo: "" },
  { id: "nu", name: "Northern University Bangladesh", short: "NUB", logo: "" },
  { id: "prime", name: "Prime University", short: "PU", logo: "" },
  { id: "swu", name: "Southern University Bangladesh", short: "SUB", logo: "" },
];

export const defaultForm = (): FormState => ({
  documentType: "lab-report",
  selectedUniId: "uu",
  institutionName: "Uttara University",
  department: "",
  subjectName: "",
  subjectCode: "",
  experimentNo: "",
  assignmentNo: "",
  itemTitle: "",
  teacherName: "",
  teacherDesignation: "",
  studentName: "",
  studentId: "",
  batchGroup: "",
  section: "",
  submissionDate: new Date().toISOString().slice(0, 10),
});
